PJT/PJT06/skeleton/accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"
urlpatterns = [
    # 회원가입
    path('signup/', views.signup, name="signup"),
    # 로그인
    path('login/', views.login, name="login"),
    # 로그아웃
    path('logout/', views.logout, name="logout"),
    # 팔로우 데이터 저장 및 팔로우 데이터 삭제
    path('<int:user_pk>/follow/', views.follow, name="follow"),
    path('<int:user_pk>', views.profile, name='profile')

]

PJT/PJT06/skeleton/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')
    
    

PJT/PJT06/skeleton/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm

# model 선택 세 가지 방법
# 1. 직접 가져오기 -> 권장 x
# from .models import User

# 2. settings에 설정된 모델 가져오기
# from django.conf import settings # model = settings.AUTH_USER_MODEL
# -> 문자열 -> models.py 에 작성할 때는 문자열로 적는게 좋다!

# 3. get_user_model 메서드 활용
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        

PJT/PJT06/skeleton/accounts/views.py
from django.shortcuts import render,redirect
from django.views.decorators.http import require_http_methods, require_POST
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserCreationForm
from django.contrib.auth import get_user_model

@require_http_methods(['GET','POST'])
def signup(request):
    # 로그인한 사용자가 들어오면???
    if request.user.is_authenticated:
        return redirect("boards:index")
    

    # METHOD 가 GET 일 때와  POST 일 때
    # POST:  실제로 회원 가입 진행
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            # 저장 및 자동로그인
            user = form.save()
            auth_login(request,user)
            return redirect("boards:index")
        
    # GET : 회원가입 페이지 보여줘야함
    else:
        form = CustomUserCreationForm()
    context = {
        'form':form,
    }
    return render(request, 'accounts/signup.html', context)


@require_http_methods(['GET','POST'])
def login(request):
    # 로그인한 사용자가 들어오면???
    if request.user.is_authenticated:
        return redirect("boards:index")
    
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect("boards:index")
        
    # GET : 회원가입 페이지 보여줘야함
    else:
        form = AuthenticationForm()
    context = {
        'form':form,
    }
    return render(request, 'accounts/login.html', context)


# 세션 데이터를 삭제하네? -> POST
@login_required
@require_POST
def logout(request):
    # 로그인 된 사용자만 로그아웃
    
    auth_logout(request)
    return redirect("boards:index")
    
    

@require_POST
def follow(request,user_pk):
    User = get_user_model()
    person = User.objects.get(pk=user_pk)
    if person != request.user:
        if request.user in person.followers.all():
            person.followers.remove(request.user)
        else:
            person.followers.add(request.user)
    return redirect('accounts:profile', person.pk)

def profile(request,user_pk):
    person = get_user_model().objects.get(pk=user_pk)
    context={
        'person' : person
    }
    return render(request, 'accounts/profile.html',context)

PJT/PJT06/skeleton/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<div>
  <h1 class="mb-4">로그인</h1>
  <form action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-light">로그인</button>
  </form>
</div>
{% endblock content %}

PJT/PJT06/skeleton/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ person.username }}님의 프로필페이지</h1>
<br>
<br>
<hr>
<p>회원번호 : {{ person.id }}</p>
<p>유저이름 : {{ person.username }}</p>
<p>가입날짜 : {{ person.date_joined }}</p>
<hr>
<p><h2>유저가 쓴 글</h2></p>

{% if person.board_set.all %}
{% for board in person.board_set.all %}
    <p>글번호 : {{ board.id }}</p>  
    <p>글제목 : <a href="{% url 'boards:detail' board.id %}" style="text-decoration: none;">{{ board.title }}</a></p>
    
  {% endfor %}
{% else %}
<p>아직 게시글이 없습니다</p>
  
  {% endif %}
  <hr>
<p><h2>유저가 쓴 댓글</h2></p>
{% if person.comment_set.all %}
{% for comment in person.comment_set.all %}
    <p>댓글 : {{ comment.content }}</p>  
    {% endfor %}
    {% else %}
    <p>아직 댓글이 없습니다</p>
    {% endif %}
    
<hr>
<div>
  <p>팔로워</p>
  <div>
    팔로잉 : {{ person.followings.all|length }} / 팔로워 : {{ person.followers.all|length}}
  </div>
  {% if request.user != person %}
  <div>
    <form action="{% url "accounts:follow" person.pk %}" method="POST">
      {% csrf_token %}
      {% if request.user in person.followers.all %}
        <input type="submit" value="팔로우취소">
      {% else %}
      <input type="submit" value="팔로우">
      {% endif %}
    </form>
  </div>
  {% endif %}
</div>
{% endblock content %}

PJT/PJT06/skeleton/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<div>
  <h1 class="mb-4">회원가입</h1>
  <form action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-light">회원가입</button>
  </form>
</div>
{% endblock content %}